version: '3.9'

volumes:
  postgres_data:

services:
  backend:
    build: .
    command: gunicorn stocks_products.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/code
    depends_on:
      - postgres
    env_file:
      - .env

  postgres:
    image: 'postgres'
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./logs:/var/logs
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin1 -d newdb" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
