version: '3.1'

networks:
  dev_network:

services:
  redis:
    image: redis:7.0.0-alpine3.15
    ports:
      - "6379:6379"
    networks:
      dev_network:
        aliases:
          - db-redis

  app:
    build:
      context: .
    environment:
      BACKEND: ${BACKEND}
      BROKER: ${BROKER}

    ports:
      - "5000:5000"
    depends_on:
      - redis
    networks:
      dev_network:
        aliases:
          - app
    volumes:
      - ./app:/app

  celery:
    build:
      context: .
    environment:
      BACKEND: ${BACKEND}
      BROKER: ${BROKER}
    entrypoint: celery -A app.celery_app worker
    depends_on:
      - redis
    networks:
      dev_network:
        aliases:
          - app
    volumes:
      - ./app:/app


  tests:
    build:
      context: .
      dockerfile: Dockerfile.tests
    environment:
      API_URL: ${API_URL}
    depends_on:
      - app
      - celery
    networks:
      dev_network:
    volumes:
      - ./app:/app